apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-19T17:42:56Z"
  generation: 2
  labels:
    app: hello
  name: hello-app
  namespace: default
  resourceVersion: "2246"
  selfLink: /apis/apps/v1/namespaces/default/deployments/hello-app
  uid: 0afb4cb6-a6b5-4ec2-b82e-11c1ba4849fc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello
    spec:
      containers:
      - image: gcr.io/cloud-com-294113/github.com/mahmad-lu/test@sha256:a184af4bd35106830adc7246a1b115aaf417ca018b6c78b275902928a7880c80
        imagePullPolicy: IfNotPresent
        name: test-sha256-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-19T17:44:31Z"
    lastUpdateTime: "2020-11-19T17:44:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-19T17:42:56Z"
    lastUpdateTime: "2020-11-19T17:44:31Z"
    message: ReplicaSet "hello-app-7d96b4fd45" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
